### ISSUE TITLE
Should not all the module commands have a common prefix, say, CoApp?

### ISSUE THREAD

**Issue by nightroman** [coapp/coapp.powershell#56]
Should not all the module commands have a common prefix, say, _CoApp_ (or _CA_, _Caps_, etc.), as it is recommended by PowerShell guidelines?

For example, here is the very recent reminder from Jeffrey Snover and John Slack at [PowerShell Team Blog](http://blogs.msdn.com/b/powershell/archive/2014/04/07/what-s-in-a-name-using-the-ps-prefix.aspx)

I afraid some current commands have too common names and conflicts will be quite possible. They will either break something for some users or will be more difficult to use themselves in some cases.

**Comment by fearthecowboy** [comment]
That is a good point. 

Although, I had thought that my choices for cmdlet names was pretty narrow, and wouldn't likely have caused collision.

However, having come a long way since I initially wrote those, I agree, there should be some better naming in these. 

I was thinking that I should split some of this stuff up too, but I'm pretty constrained on time these days.

**Comment by nightroman** [comment]
Thank you for the quick response. In particular, the name `Invoke-Build` seems to be too common. It conflicts with one of my tools, for example. I would not be surprised if many others already have such a command in their PowerShell tool sets.

**Comment by fearthecowboy** [comment]
On my next pass coding, I'll try to rename that one. I don't think anyone else uses it anyway :)
